image: python:3
lint:
  stage: test
  script:
  - pip install yapf==0.32.0
  - yapf --recursive . -i --style google
  only:
  - merge_requests

unittest:
  stage: test
  needs:
  - pipeline: test
    job: lint
  script:
  - pip install -r requirements.txt
  - pytest .
  only:
  - merge_requests

prod:
image: google/cloud-sdk:alpine
stage: deploy
needs:
- pipeline: test
  job: unittest
environment: Production
only:
- main
script:
- echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
- gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
- gcloud --quiet --project $PROJECT_ID app deploy