image: python:3
lint:
  stage: test
  script:
  - pip install yapf==0.32.0
  - yapf --recursive . -i --style google
  only:
  - pushes

unittest:
  stage: test
  needs:
  - pipeline: test
    job: lint
  script:
  - pip install -r requirements.txt
  - pip install -U Flask-WTF
  - pytest .
  only:
  - pushes